### ISSUE TITLE
ios能用么

### ISSUE THREAD

**Issue by JiweiMaster** [befovy/flutter_volume#1]
TODO #
Make it iOS compatible (help is appreciated!)

我有点慌

**Comment by JiweiMaster** [comment]
Unhandled Exception: MissingPluginException(No implementation found for method volume on channel flutter_volume)

**Comment by befovy** [comment]
iOS 和 Android 都可以用的，gif 动图不就是 iOS 么

**Comment by befovy** [comment]
对此问题如果有任何疑问，可以重新打开 issue @JiweiMaster
