### ISSUE TITLE
Not working on ios 

### ISSUE THREAD

**Issue by vivaan-m** [befovy/flutter_volume#2]
it is working well on android but in ios it doesn't update volume

**Comment by befovy** [comment]
Please provide steps to reproduce

**Comment by vivaan-m** [comment]
Included Your Plugin image below :
![Screenshot 2020-03-17 at 4 23 24 PM](https://user-images.githubusercontent.com/53035502/76849652-cc80bd80-686b-11ea-8d21-795af067d04a.png)
after that copied your example code into it  image below :
![Screenshot 2020-03-17 at 4 23 48 PM](https://user-images.githubusercontent.com/53035502/76849694-e1f5e780-686b-11ea-85cb-ff4406361d0f.png)
after that when i run it on iphone 11 (13.2)(simulator) it do show the buttons and slider but doesn't increase or decrease volume in device 


Flutter Doctor Image Below:
![Screenshot 2020-03-17 at 4 30 39 PM](https://user-images.githubusercontent.com/53035502/76850154-cc34f200-686c-11ea-96f6-63ccc1384fa2.png)

**Comment by befovy** [comment]
this plugin dose not support simulator

**Comment by vivaan-m** [comment]
oh okay thanks i will try it on real device 👍
