### ISSUE TITLE
kotlin_version

### ISSUE THREAD

**Issue by fl-oe** [befovy/flutter_volume#3]
It is possible to increase ext.kotlin_version?
I had issues while building my project with kotlin_version 1.3.61.
If I change the version to 1.3.61 in file
"External Libraries/Flutter Plugins/sys_volume-0.1.0/android/src/main/build.gradle" everything works fine.

Change required in "sys_volume-0.1.0/android/src/main/build.gradle" file. Set ext.kotlin_version to '1.3.61'

**Comment by befovy** [comment]
Yes, you can open a pull request

**Comment by htaptit** [comment]
@befovy 
https://github.com/befovy/flutter_volume/pull/4
