### ISSUE TITLE
happend a exception

### ISSUE THREAD

**Issue by ModWU** [befovy/flutter_volume#6]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_volume' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.51

**Comment by befovy** [comment]
This repo is just sample code for blog.
Please fork and make your own flutter library
