### ISSUE TITLE
type is invalid?

### ISSUE THREAD

**Issue by lix-wood** [befovy/flutter_volume#8]
FlutterVolume.set(double vol, type: FlutterVolume.RING )  这个type 是设置是否为铃声/媒体/闹钟等声音的吗？如果是，为什么不生效呢

**Comment by befovy** [comment]
type 在 iphone 上不生效

**Comment by befovy** [comment]
这个仓库仅仅是一个博客附带的代码。有什么问题都可以自己看看代码
